/**
 * Regenerates the derived data files:
 *
 *   src/data/contentSummaries.js  — postSummaries (excerpt + readingMinutes)
 *   src/data/libraryIndex.js      — homepage counts and lead lines
 *
 * Run with `npm run data` after editing posts, projects or books.
 *
 * The point of both files is bundle weight: list pages and the homepage read
 * from these small modules so the full content of posts.js (~94KB) and
 * books.js (~18KB) stays in the lazy route chunks that actually need it.
 */
import { readFileSync, writeFileSync, copyFileSync, mkdtempSync, rmSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { tmpdir } from 'node:os';

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const STAGE = mkdtempSync(join(tmpdir(), 'mk-data-'));

/**
 * The data modules use ESM syntax but live in a CommonJS package, so Node will
 * not import them as-is. Staging them under an .mjs name is the cheapest way to
 * read them without pulling a bundler into the build.
 */
const load = async (relativePath, name) => {
  const staged = join(STAGE, `${name}.mjs`);
  copyFileSync(join(REPO, relativePath), staged);
  return import(pathToFileURL(staged).href);
};

const MONTHS = ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'];

// Dates appear as "Sep 4, 2025", "Jan 14 2025", "May 2023" and "Mar, 2025".
const parseDate = (value) => {
  const text = String(value || '').trim().toLowerCase().replace(/,/g, ' ');
  const month = MONTHS.indexOf((text.match(/[a-z]+/) || [''])[0].slice(0, 3));
  const year = text.match(/\b(\d{4})\b/);
  if (month < 0 || !year) return 0;

  const day = text.match(/\b(\d{1,2})\b/);
  return Date.UTC(Number(year[1]), month, day ? Number(day[1]) : 1);
};

const newest = (items) => [...items].sort((a, b) => parseDate(b.date) - parseDate(a.date))[0];

const serialize = (record, indent = '    ') =>
  Object.entries(record)
    .map(([key, value]) => `${indent}${key}: ${JSON.stringify(value)},`)
    .join('\n');

try {
  const { posts } = await load('src/data/posts.js', 'posts');
  const { getExcerpt, getReadingMinutes } = await load('src/utils/content.js', 'content');
  const { researchPaperSummaries } = await load('src/data/contentSummaries.js', 'summaries');
  const { projectSummaries } = await load('src/data/projectSummaries.js', 'projects');
  const { books } = await load('src/data/books.js', 'books');

  // --- contentSummaries.js: postSummaries -----------------------------------
  const postSummaries = posts.map((post) => ({
    id: post.id,
    title: post.title,
    date: post.date,
    excerpt: getExcerpt(post.content, 180),
    readingMinutes: getReadingMinutes(post.content),
  }));

  const summariesPath = join(REPO, 'src/data/contentSummaries.js');
  const existing = readFileSync(summariesPath, 'utf8');
  const marker = 'export const postSummaries = ';
  const preserved = existing.slice(0, existing.indexOf(marker));
  const postBody = postSummaries.map((s) => `  {\n${serialize(s)}\n  },`).join('\n');

  writeFileSync(summariesPath, `${preserved}${marker}[\n${postBody}\n];\n`);

  // --- libraryIndex.js ------------------------------------------------------
  const latestPost = newest(postSummaries);
  const latestPaper = newest(researchPaperSummaries);
  const latestProject = newest(projectSummaries);
  const categories = [...new Set(books.map((book) => book.category))];

  const index = [
    {
      key: 'posts',
      label: 'Articles',
      to: '/posts',
      count: postSummaries.length,
      unit: 'essays',
      lead: latestPost.title,
      meta: latestPost.date,
    },
    {
      key: 'ideas',
      label: 'Ideas',
      to: '/ideas',
      count: researchPaperSummaries.length,
      unit: 'papers',
      lead: latestPaper.title,
      meta: latestPaper.date,
    },
    {
      key: 'projects',
      label: 'Projects',
      to: '/projects',
      count: projectSummaries.length,
      unit: 'builds',
      lead: latestProject.name,
      meta: latestProject.date,
    },
    {
      key: 'books',
      label: 'Books',
      to: '/books',
      count: books.length,
      unit: 'shelved',
      lead: `${categories.slice(0, 4).join(' · ')}${categories.length > 4 ? ' · …' : ''}`,
      meta: '',
    },
  ];

  const indexBody = index.map((entry) => `  {\n${serialize(entry)}\n  },`).join('\n');

  writeFileSync(
    join(REPO, 'src/data/libraryIndex.js'),
    `/**
 * Generated by \`npm run data\` — do not edit by hand.
 *
 * Counts and lead lines for the homepage index, kept as their own small module
 * so the homepage can show the shape of the site without pulling the full
 * posts, projects and books data into the main bundle.
 */
export const libraryIndex = [\n${indexBody}\n];\n`
  );

  console.log(`contentSummaries.js — ${postSummaries.length} posts`);
  postSummaries.forEach((s) => console.log(`  ${String(s.readingMinutes).padStart(2)} min  ${s.title}`));
  console.log('\nlibraryIndex.js');
  index.forEach((e) => console.log(`  ${e.label.padEnd(9)} ${String(e.count).padStart(3)} ${e.unit.padEnd(8)}  ${e.lead}`));
} finally {
  rmSync(STAGE, { recursive: true, force: true });
}
